maxJobs: 100

outputDir: 'path/to/outputdir' 

clusterMode: 'cluster' or 'gcp' 

useRemoteFiles: FALSE

refGenome: 'path/to/ref/fasta'
bedFile: 'path/to/bedfile'
bedFileGZ: '/path/to/gzippedBedFile'

runMode:
  streka2: TRUE
  haplotypeCaller: TRUE
  deepVariant: TRUE
  harmonize: FALSE  # will only be run if both callers are used

by_chrom: TRUE #if you like the workflow to be run by chromosome, FALSE if you like to to be run by sample
threads: 8

# DeepVariant parameters
model_type: PACBIO or WGS or WES

# Strelka2 parameters
glnexusConfig: 'full/path/to/strelka2_glnexus.yml'
exome_param: # '--exome' if it's WES, otherwise ''
memGB: 16
