maxJobs: 100

outputDir: './' #set it to current dir (./) if running on a cluster, or to a gs storage bucket if running on GCP 

clusterMode: 'cluster' or 'gcp' 

useRemoteFiles: FALSE

refGenome: 'path/to/ref/fasta'
bedFile: 'path/to/bedfile'
bedFileGZ: '/path/to/gzippedBedFile'

runMode:
  streka2: TRUE
  haplotypeCaller: TRUE
  deepVariant: TRUE
  harmonize: FALSE  # will only be run if both callers are used

by_chrom: TRUE #if you like the workflow to be run by chromosome, FALSE if you like to to be run by sample
threads: 8

# DeepVariant parameters
model_type: PACBIO or WGS or WES
deepvariant_memGB: 32 #it is recommended that this memory to be set to roughly the same as the BAM file size

# Strelka2 parameters
glnexusConfig: 'full/path/to/strelka2_glnexus.yml'
exome_param: # '--exome' if it's WES, otherwise ''
strelka2_memGB: 32

